#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
Created Date: June 12. 2020
Copyright: UNMAND SOLUTION
Author: Dae Jong Jin 
Description: PCAN 통신
'''
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from umd_can import UMDCan

"""
예외 처리
"""
class CustomException(Exception):
    def __init__(self, value):
        self.value = value
    
    def __str__(self):
        return self.value

def raise_exception(err_msg):
    raise CustomException(err_msg)

"""
MAIN
"""
def main():
    print ("pcan to relay v 1.0.0")

    uc = UMDCan()
    # while True:

    try :
        while True:
            try :
                degree = int(input("원하는 각도를 입력하세요(90도 이하의 각도):  "))
                if  degree <= 0 or degree >90:
                    raise_exception("90이하로 입력하세요")
                else:80
                    uc.run(degree)
                    
            except CustomException as e:
                print(e)
            except :
                print("잘못된 입력입니다.")

    except KeyboardInterrupt:
        print("프로그램 종료")

if __name__ == "__main__":
    main()
